kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  namespace: expense
  # these labels are deployment related labels
  labels:
    component: backend
    project: expense
    tier: backend
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      component: backend
      project: expense
      tier: backend
  # pod definition
  template:
    metadata:
      labels:
        component: backend
        project: expense
        tier: backend
        environment: dev
    spec:
      containers:
      - name: backend
        image: mallurumamatha/backend:{{ .Values.deployment.imageVersion }} ### give the image which you build from docker
        envFrom:
        - configMapRef:
            name: backend